### ISSUE TITLE
Icons are clipping in awesomewm-vertical on ArchLinux

### ISSUE THREAD

**Issue by llyram** [AlphaTechnolog/dotfiles-v2#9]
![image](https://user-images.githubusercontent.com/56125520/195024149-a454e09d-6eea-4d76-b42d-c28fe9eac3ae.png)

I have installed both the nerd fonts as instructed in the readme.
As you can see some icons are sized correctly like the brightness and volume slider icons but others are clipping in their containers.

I have not modified anything in the config.

I am using this config on Arch linux, with a screen size of 1920x1080

**Comment by AlphaTechnolog** [comment]
hm, i don't really know why the fonts aren't working in this case :/ maybe i forget to include some fonts xD, try installing the `nerd-fonts-complete` from the aur and restarting completely X11, if that doesn't works too, i'll need a bit more of time to reproduce it installing arch. Also, sorry for late response. :/

**Comment by Griffith-Femto** [comment]
I'm having the same issue installing nerd-fonts-complete doesn't help, amazing rice btw

**Comment by polipolo55** [comment]
im having the exact same issue on the latest arch build

**Comment by fithurriague** [comment]
> im having the exact same issue on the latest arch build

Me too, the exact same but in horizontal layout

**Comment by AlphaTechnolog** [comment]
Hm sorry guys, i have to reproduce it in arch then :v

**Comment by fithurriague** [comment]
Any update on this issue? I suggest to change the title to "Icons clipping on ArchLinux". Also, temperature doesn't work, can someone confirm? I can fix it for arch, but the right thing to do would be start looking for a long term solution, an os and cpu architecture independent one. What do you guys think?

**Comment by AlphaTechnolog** [comment]
> Any update on this issue? I suggest to change the title to "Icons clipping on ArchLinux". Also, temperature doesn't work, can someone confirm? I can fix it for arch, but the right thing to do would be start looking for a long term solution, an os and cpu architecture independent one. What do you guys think?

Not yet, i didn't had enough time to try to make a fix (or at least install arch on a virtual machine) because i'm in exams :v (sorry for that y'all). Also, i'll try to make a fix for the temperature, but for that i'll need some details, can you open another issue showing some details of the issue? like what the temperature widget do and that stuff.

**Comment by AlphaTechnolog** [comment]
Also, about the clipping of the icons, can you guys check if the icons clipping problem just happens with the UI of the rice, or it's still happening on others Apps too?

**Comment by Underscore30** [comment]
I'm also getting this problem in Void Linux. Installed it on a VM to test it out and am getting the same icon clipping problem. Installed the fonts from the readme and also from the xbps nerd-fonts.

**Comment by polipolo55** [comment]
> Also, about the clipping of the icons, can you guys check if the icons clipping problem just happens with the UI of the rice, or it's still happening on others Apps too?

It was just happening on the rice but i didn't have much more installed at the moment of trying

**Comment by AlphaTechnolog** [comment]
Ok so I've reproduced in a new freshly installed arch Linux, looks like an update on the nerd fonts, I've got a fix for that, I'll push the changes asap, i think i have to change the nerd font, jet brains looks rare lol

**Comment by AlphaTechnolog** [comment]
ok i pushed the changes, can you guys recheck if with `Iosevka Nerd Font` works better?

**Comment by fithurriague** [comment]
Hi! Can you push the fix to the awesomewm branch too?

**Comment by AlphaTechnolog** [comment]
> ok i pushed the changes, can you guys recheck if with `Iosevka Nerd Font` works better?

yeah sure, it's done, try pulling the changes and copy again `cfg/awesome` to `~/.config/`

**Comment by fithurriague** [comment]
It actually did not solve the problem. It's just a different kind of clipping now, I would say it's worse. I'd also love to see other people following the issue so we could get more feedback.

*Edit: I'm inspecting under `~/.config/awesome/ui/bar/init.lua` where the container is defined, and inside `action-icons/` where each icon is and it's placement is defined. But I can't find the problem. As @AlphaTechnolog suspected at first it seems to be a font problem... but changing the font to Iosevka solve nothing at least for me.

**Comment by AlphaTechnolog** [comment]
@fithurriague thanks for your debugging and for every time that you're spending on this for help me! I suspected that iosevka wouldn't solve the problem for this, for some reason on void Linux worked to me, but i think that this could be a problem on an update of NF, because on void i had an outdated version of it, i tried on a fresh arch install and the problem appeared, i solved it by setting `theme.nerd_font` to an inexistent font (such as Iosevka which i didn't installed on that system) (those changes inside cfg/awesome/theme.lua). Anyways this is so weird because icons aren't working like how should work :/

Don't makes sense that an inexistent font worked and displayed every icon in the UI (and avoided this issue)

So tbh I'll need a very good time of debugging to try to get this working, because i don't understand too much the font issue lol

As @fithurriague said, more ppl feedback could be good for some investigation about this because is so strange and happens on every awesomewm rice :v

**Comment by Underscore30** [comment]
I am trying this on OpenSUSE and had the same icon clipping issue while using the Nerd Fonts v2.2.2. However, when I downgraded to the 2.2.1 version it now started working as intended. 

This is definitely an issue with the new version of the Nerd Fonts.  Also, I tried the 2.3.0RC version they have up and the issue still persists, I guess it only works with the 2.2.1 version.

For anyone having this issue, you can go to the [Nerd Fonts github](https://github.com/ryanoasis/nerd-fonts), download the 2.2.1 release, unpack it to /.fonts and in the terminal run fc-cache -fv.

**Comment by AlphaTechnolog** [comment]
Ok so, as I supposed and as @Underscore30 says, it's a nerdfonts update issue.... so i'll need to rework a "little" bit more the configuration to make it look better with the newer ones lol, a temporary fix guys is downgrade the nerdfonts as how @Underscore30 said

**Comment by quiltedstars** [comment]
@AlphaTechnolog Sorry to disappoint, but the font issue is also happening for me on Void Linux!

**Comment by AlphaTechnolog** [comment]
> @AlphaTechnolog Sorry to disappoint, but the font issue is also happening for me on Void Linux!

they could have updated the nerd fonts then... so basically these dotfiles are running under an outdated version of nerdfonts? maybe some refactor is needed then. People's help is actually heavily appreciated tho! anyways imma try to fix it asap.
